name: Laravel

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # install and set up laravel and php8.0
      - name: Update apt-get
        run: sudo apt-get update
      - name: Install PHP
        run: sudo apt-get install php8.0-cli php8.0-xml php8.0-mbstring php8.0-json php8.0-curl php8.0-sqlite3

      - name: Install Composer
        run: wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet
      - name: Move Composer to bin
        run: sudo mv composer.phar /usr/local/bin/composer
      - name: Install Laravel
        run: composer global require laravel/installer
      - name: Add Composer bin to PATH
        run: export PATH="$HOME/.config/composer/vendor/bin:$PATH"

      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Update composer
        run: composer update
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
